In [4]:
import pandas as pd

In [5]:
db1=pd.read_csv("used_cars.csv")
db2=pd.read_csv("voitures_occasion.csv")
db3=pd.read_csv("voitures_occasion_xl.csv")

In [6]:
db1.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,Ford,Utility Police Interceptor Base,2013,"51,000 mi.",E85 Flex Fuel,300.0HP 3.7L V6 Cylinder Engine Flex Fuel Capa...,6-Speed A/T,Black,Black,At least 1 accident or damage reported,Yes,"$10,300"
1,Hyundai,Palisade SEL,2021,"34,742 mi.",Gasoline,3.8L V6 24V GDI DOHC,8-Speed Automatic,Moonlight Cloud,Gray,At least 1 accident or damage reported,Yes,"$38,005"
2,Lexus,RX 350 RX 350,2022,"22,372 mi.",Gasoline,3.5 Liter DOHC,Automatic,Blue,Black,None reported,NaN,"$54,598"
3,INFINITI,Q50 Hybrid Sport,2015,"88,900 mi.",Hybrid,354.0HP 3.5L V6 Cylinder Engine Gas/Electric H...,7-Speed A/T,Black,Black,None reported,Yes,"$15,500"
4,Audi,Q3 45 S line Premium Plus,2021,"9,835 mi.",Gasoline,2.0L I4 16V GDI DOHC Turbo,8-Speed Automatic,Glacier White Metallic,Black,None reported,NaN,"$34,999"

In [7]:
db2.head()

,id,marque,modele,annee,kilometrage,carburant,boite,puissance_ch,carrosserie,nb_portes,couleur,nb_proprietaires,accident,controle_technique,vendeur,region,conso_l_100km,emissions_co2_g_km,prix_eur
0,1,Audi,A1,2017,87820,Hybride,Automatique,160,Citadine,5,Noir,3.0,Non,Valide,Particulier,Ile-de-France,5.9,139.0,10720
1,2,Volkswagen,Passat,2012,188480,Diesel,Manuelle,220,Berline,5,Noir,4.0,Non,A refaire,Professionnel,Ile-de-France,5.9,159.0,8030
2,3,Fiat,500,2008,290550,Essence,Manuelle,100,Citadine,3,NaN,2.0,Non,Valide,Particulier,PACA,4.7,112.0,1910
3,4,Mercedes,GLA,2021,74770,Essence,Automatique,220,SUV,5,Argent,2.0,Non,Valide,Particulier,Ile-de-France,8.0,189.0,26560
4,5,Renault,Captur,2021,101530,Essence,Manuelle,170,SUV,5,Argent,1.0,Non,Valide,Professionnel,Hauts-de-France,7.3,168.0,14320

In [8]:
db3.head()

,id,marque,modele,carrosserie,annee,mois_mise_en_circulation,kilometrage,carburant,boite,puissance_ch,...,jantes_pouces,garantie_mois,vendeur,ville,departement,region,date_annonce,nb_photos,jours_en_ligne,prix_eur
0,1,Toyota,RAV4,SUV,2018,12,123550,Hybride,Manuelle,230,...,17,0,Professionnel,Bordeaux,33,Nouvelle-Aquitaine,2025-02-07,10,6,14240
1,2,Dacia,Spring,SUV,2015,10,300170,Electrique,Automatique,120,...,15,0,Professionnel,Paris,75,Ile-de-France,2025-05-04,10,42,4640
2,3,Mercedes,GLC,SUV,2025,6,13530,Diesel,Manuelle,320,...,18,0,Professionnel,Metz,57,Grand Est,2025-08-19,10,53,59820
3,4,Peugeot,308,Compacte,2014,11,73480,Diesel,Manuelle,170,...,16,6,Professionnel,Rouen,76,Normandie,2026-07-16,21,14,5200
4,5,Peugeot,3008,SUV,2019,10,32090,Electrique,Automatique,210,...,16,0,Particulier,Metz,57,Grand Est,2025-02-24,12,5,19960

In [9]:
db1.describe()

        model_year
count  4009.000000
mean   2015.515590
std       6.104816
min    1974.000000
25%    2012.000000
50%    2017.000000
75%    2020.000000
max    2024.000000

In [10]:
db2.describe()

,id,annee,kilometrage,puissance_ch,nb_portes,nb_proprietaires,conso_l_100km,emissions_co2_g_km,prix_eur
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,9561.000000,8851.000000,9707.000000,10000.000000
mean,5000.50000,2018.705400,103151.190000,167.759000,4.900600,2.417425,6.545396,140.442876,14623.848000
std,2886.89568,4.693252,83738.213427,54.145555,0.434671,1.418905,1.368063,59.298514,9879.326208
min,1.00000,2008.000000,500.000000,70.000000,3.000000,1.000000,3.200000,0.000000,1200.000000
25%,2500.75000,2015.000000,38632.500000,130.000000,5.000000,1.000000,5.500000,125.000000,7190.000000
50%,5000.50000,2019.000000,79780.000000,160.000000,5.000000,2.000000,6.400000,149.000000,12310.000000
75%,7500.25000,2023.000000,145620.000000,200.000000,5.000000,3.000000,7.500000,177.000000,19740.000000
max,10000.00000,2025.000000,380000.000000,450.000000,5.000000,6.000000,12.500000,306.000000,64240.000000

In [11]:
db3.describe()

,id,annee,mois_mise_en_circulation,kilometrage,puissance_ch,cylindree_cm3,nb_cylindres,couple_nm,poids_kg,longueur_mm,...,capacite_batterie_kwh,autonomie_km,nb_proprietaires,nb_airbags,jantes_pouces,garantie_mois,departement,nb_photos,jours_en_ligne,prix_eur
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,196005.000000,200000.000000,200000.000000,...,21039.000000,21039.000000,192218.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,100000.500000,2018.690390,6.496975,104471.062900,168.613450,1437.444050,3.492720,336.001571,2263.238100,5021.297450,...,40.110357,209.982414,2.426568,5.807980,16.531525,4.705950,50.303120,9.998890,27.411135,15085.905600
std,57735.171256,4.698668,3.444673,84398.135962,52.519927,685.736315,1.458258,108.920902,363.283144,160.736661,...,15.902796,85.797759,1.433625,1.736382,0.951073,6.352679,25.247175,3.161863,27.726930,10342.465603
min,1.000000,2008.000000,1.000000,500.000000,60.000000,0.000000,0.000000,94.000000,1310.000000,4270.000000,...,20.000000,50.000000,1.000000,2.000000,14.000000,0.000000,6.000000,1.000000,1.000000,1200.000000
25%,50000.750000,2015.000000,4.000000,38600.000000,130.000000,1100.000000,3.000000,256.000000,2030.000000,5100.000000,...,27.300000,140.000000,1.000000,4.000000,16.000000,0.000000,31.000000,8.000000,7.000000,7180.000000
50%,100000.500000,2019.000000,6.000000,81960.000000,160.000000,1470.000000,4.000000,320.000000,2370.000000,5100.000000,...,36.900000,190.000000,2.000000,6.000000,17.000000,0.000000,49.000000,10.000000,19.000000,12570.000000
75%,150000.250000,2023.000000,9.000000,148340.000000,200.000000,1840.000000,4.000000,398.000000,2600.000000,5100.000000,...,50.800000,270.000000,3.000000,8.000000,17.000000,6.000000,75.000000,12.000000,38.000000,20520.000000
max,200000.000000,2025.000000,12.000000,380000.000000,450.000000,4000.000000,8.000000,1177.000000,2600.000000,5100.000000,...,99.800000,560.000000,6.000000,8.000000,20.000000,24.000000,93.000000,28.000000,180.000000,78030.000000